# Generated by Django 5.2.7 on 2025-11-16 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("addr", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("price", models.SmallIntegerField()),
                ("period", models.PositiveSmallIntegerField()),
                ("outline", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClassList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.PositiveSmallIntegerField(verbose_name="Semester")),
                ("start_date", models.DateField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM.branch"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                ("qq", models.CharField(max_length=64, unique=True)),
                ("qq_name", models.CharField(blank=True, max_length=64, null=True)),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "source",
                    models.SmallIntegerField(
                        choices=[
                            (0, "referral"),
                            (1, "QQchatGroup"),
                            (2, "officialWebsite"),
                            (3, "BaiduPromotion"),
                            (4, "51CTO"),
                            (5, "ZhiHu"),
                            (6, "MarketPromotion"),
                        ]
                    ),
                ),
                (
                    "referral_form",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="referralQQ"
                    ),
                ),
                ("content", models.TextField(verbose_name="ConsultDetail")),
                ("note", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "consult_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.course",
                        verbose_name="consultCourse",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="CRM.tag")),
            ],
            options={
                "verbose_name": "客户表",
                "verbose_name_plural": "客户表",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("roles", models.ManyToManyField(blank=True, to="CRM.role")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(default=500, verbose_name="Amount"),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM.customer"
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_agreed",
                    models.BooleanField(
                        default=False, verbose_name="the student agreed"
                    ),
                ),
                (
                    "contract_approved",
                    models.BooleanField(
                        default=False, verbose_name="contract reviewed"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM.customer"
                    ),
                ),
                (
                    "enrolled_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.classlist",
                        verbose_name="enrolled class",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.userprofile",
                        verbose_name="consultant",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "enrolled_class")},
            },
        ),
        migrations.CreateModel(
            name="CustomerFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="What to follow up")),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "intention",
                    models.SmallIntegerField(
                        choices=[
                            (0, "apply within two weeks"),
                            (1, "apply within 1 month"),
                            (2, "no intention"),
                            (3, "enrolled in other institutions"),
                            (4, "enrolled"),
                            (5, "blocked"),
                        ]
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM.customer"
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="consultant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CRM.userprofile"
            ),
        ),
        migrations.CreateModel(
            name="CourseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_num", models.PositiveSmallIntegerField(verbose_name="Which day")),
                ("got_homework", models.BooleanField(default=True)),
                (
                    "homework_title",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("homework_content", models.TextField(blank=True, null=True)),
                ("outline", models.TextField(verbose_name="This course's outline")),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "from_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.classlist",
                        verbose_name="Class",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_class", "day_num")},
            },
        ),
        migrations.AddField(
            model_name="classlist",
            name="teacher",
            field=models.ManyToManyField(to="CRM.userprofile"),
        ),
        migrations.CreateModel(
            name="StudyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance",
                    models.SmallIntegerField(
                        choices=[
                            (0, "signed"),
                            (1, "late"),
                            (2, "absent"),
                            (3, "drop off"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "score",
                    models.SmallIntegerField(
                        choices=[
                            (100, "A+"),
                            (90, "A"),
                            (85, "B+"),
                            (80, "B"),
                            (75, "B-"),
                            (70, "C+"),
                            (60, "C"),
                            (40, "C-"),
                            (-50, "D"),
                            (-100, "COPY"),
                            (0, "N/A"),
                        ],
                        default=0,
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "course_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.courserecord",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="CRM.enrollment"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "学习记录",
                "unique_together": {("student", "course_record")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="classlist",
            unique_together={("branch", "course", "semester")},
        ),
    ]
