# Generated by Django 5.2.7 on 2025-11-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("url_name", models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="menus",
            field=models.ManyToManyField(blank=True, to="CRM.menu"),
        ),
    ]
